#
# Constantin Knizhnik
# Moscow Software Center
# BGI for Windows
#

DEFINES = 
CC = bcc32 +bcc32.cfg

# Debug
#CCFLAGS = -I. -Od -c -v $(DEFINES)

# Optimize
CCFLAGS = -I. -4 -N -P -d -O2 -c -v $(DEFINES)

LD = bcc32 -v +bcc32.cfg
LDFLAGS =  -L"C:\Borland\Bcc55\lib"

all: hexedit.exe

hexedit.obj: *.cpp
	$(CC) $(CCFLAGS) hexedit.cpp 

hexedit.exe: hexedit.obj
	$(LD) $(LDFLAGS) hexedit.obj 

clean:
	delAll

